### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by xoudini** [ikuisma/TrackBack#1]
### Tietokantataulut

Tietokantataulut vaikuttavat aiheeseen liittyen järkeviltä ja `CREATE TABLE`-lauseet on toteutettu hyvin. Henkilökohtaisesti toteuttaisin liitostaulun hieman eri tavalla – vaihtamalla `PRIMARY KEY (track_id, tag_id)` tilalle `UNIQUE (track_id, tag_id)` jos molemmat sarakkeet ovat taatusti epä-tyhjiä. Näissä [ei ole oikeastaan mitään eroa](https://www.postgresql.org/docs/8.1/static/ddl-constraints.html), mutta syntaktisesti `UNIQUE` on omasta mielestäni luontevampi liitostauluihin.

Käyttäisin myös henkilökohtaisesti tekstityyppiä `TEXT` sen sijaan että määrittelisin mielivaltaisen ylärajan `VARCHAR`-tyypille, mutta tämäkin on makuasia.

### Reitit

Reitit (eli _endpoints_) ovat suhteellisen harkittuja, mutta itse tiedostossa voisi käyttää hyväksi kommentteja ja/tai whitespace:ä niin että eri osiot olisivat selvemmin eriteltyinä, esimerkiksi:

    # Tag endpoints

    $routes->get('/tags', function() {
        TagController::index();
    });

    ...

    # Track endpoints

    $routes->get('/tracks', function(){
        TrackController::index();
    });

    ...

Kun reittien määrä vielä kasvaa, niin tulee hankalammaksi löytää oikea reitti nopeasti ilman jonkinlaista osittelua.

### Mallit

Tällä hetkellä mallin `Track` tietokantakyselyissä löytyisi parannettavaa. Esimerkiksi `Tag::findForTrack($id)` voitaisiin suoraan toteuttaa liitoksina `Track`-mallin `SELECT`:issä. Lisäksi, joitakin sarakkeita ei käytetä näkymässä, jolloin `SELECT * FROM Track` on hieman liian laaja kysely.

Yleisesti `findForTrack`-metodit sekä malleissa `Track` että `Tag` ovat ehkä liiallisia. Muuten kaikki mallit ovat kohdillaan.

### Kontrollerit

Kontrollerit näyttävät hyvältä, enkä löydä mitään suurempaa kritiikkiä näistä.

### Yleistä

Koodi vaikuttaa ihan hyvän näköiseltä, vaikka ymmärrettävästi projektin vaiheeseen nähden löytyy hieman toistoa siellä sun täällä. Metodien (ja ehkä myös joidenkin reittien) nimet voisivat ehkä olla vähän deskriptiivisempiä, mutta tämäkin on tosiaan makukysymys.

Projekti näyttää hyvältä, ja front-end on hyvin designattu.

**Comment by ikuisma** [comment]
Kiitos paljon hyvästä palautteesta! 

Reitit on nyt ryhmitelty routes.php tiedostoon Slimin kivaa [groupausta](http://docs.slimframework.com/routing/groups/) käyttäen. Poistin myös ylimääräisen tiedon hakemisen kappale-listan tuottavasta kyselystä.    

Liitoskyselyiden tuottaminen on tosiaan herättänyt vähän kysymysmerkkejä sen suhteen, että miten ne olisi fiksuinta toteuttaa. Nyt yksittäisen kappaleen tuottavassa kyselyssä haen nimenomaan liitoskyselynä kaikki siihen liittyvät tag_id:t, mutta jostain syystä nykyinenkin ratkaisu näyttää aika rumalta. Jos sulla on jotain hyviä vinkkejä sen suhteen niin kuuntelen niitä mielelläni. 

Toisteisuutta tosiaan löytyy liikaa omaan makuun ja olen pohtinut, että joitakin asioita voisi ehkä yleistää ja siirtää suoraan base_controller ja base_model luokille. En nyt lähtenyt sitä toteuttamaan ihan vain siitä syystä, etten halua pudota mihinkään over-engineering sudenkuoppaan.

Jos tulee mieleen toisteisuuteen tai noihin kyselyihin liittyviä parannusehdotuksia, niin otan niitä mielelläni vastaan. Kiitos paljon palautteesta!

**Comment by xoudini** [comment]
> Reitit on nyt ryhmitelty routes.php tiedostoon Slimin kivaa groupausta käyttäen.

Näyttää hyvältä, en tiennytkään tällaisesta.

> Liitoskyselyiden tuottaminen on tosiaan herättänyt vähän kysymysmerkkejä [...]

Makuasia, ja nyt kun tarkastelin uudestaan kyselyjä, niin olihan ne kuitenkin ihan ok aiemminkin. Nyt en muista tarkkaa syytä tuohon kommenttiin.

> En nyt lähtenyt sitä toteuttamaan ihan vain siitä syystä, etten halua pudota mihinkään over-engineering sudenkuoppaan.

Varmaan ihan järkevä ratkaisu, kun näin loppusuoralla ollaan. Jos löytyy ylimääräistä aikaa niin tätä voi sitten pohtia tarkemmin.
