### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tulir** [ikuisma/TrackBack#3]
Koodi katselmoitu commitin 79d1307909c8fb1964762708a7294247d7090b3a (12.1.2018, 20:53) kohdalta.

Pääosin kaikki on kunnossa (eli en löytänyt tarpeeksi kritisoitavaa). Käyttöliittymä näyttää hyvältä. Reitit ja näkymät ovat hyvin järjesteltyjä. Kontrollereissa ei ongelmia ja funktiot on nimetty hyvin.

Kirjautumattomat käyttäjät eivät voi tehdä tageilla mitään, joten vaikuttaa turhalta, että he pystyvät luomaan ja muokkaamaan niitä. Dokumentaation käyttötapauskaaviossa ei ole mainittu mitään tageista. Jos kirjautumattomilla käyttäjillä on syitä luoda tai muokata tageja, ne voisi mainita käyttötapauksissa.

Mallit ovat muuten kunnossa, mutta:
* Huomasin hieman koodin toistoa tietokannasta luetun tiedon muuntamisessa malleiksi. `Track`-mallissa löytyykin jo funktio `trackFromRow($row)`, samaa tekniikkaa voisi käyttää kaikissa malleissa.
* SQL-kyselyn lopussa `LIMIT 1` ei haittaa, mutta on kuitenkin turha jos etsit arvoa pääavaimen perusteella, sillä tietokantaan ei voi asettaa useampaa riviä samalla pääavaimella.
* `models/hello_word.php` pitäisi varmaan poistaa

**Comment by ikuisma** [comment]
Tosiaan nuo tageihin liittyvät toiminnot kirjautumattomille käyttäjille oli vahingossa jäänyt aiemmasta versiosta kummittelemaan. Rajoitin kyseiset toiminnot vain kirjautuneille käyttäjille ja päivitän dokumentaation vastaamaan nykyistä toteutusta kohtapuolin. Tuo hello_world.php tiedosto on hävitetty ja trackFromX funktiot olivat itse asiassa täysin turhia joten poistin ne kokonaan.  

Kiitos todella paljon palautteesta!
